#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Junpei Yamamoto <s24C1133la@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause
import sys

probs = [
    "0.00", "12.50", "23.72", "33.76", "42.71", "50.66", "57.71", "63.93", "69.40", "74.19",
    "78.37", "81.99", "85.06", "87.79", "90.06", "91.98", "93.59", "94.92", "96.01", "96.90",
    "97.62", "98.20", "98.66", "99.02", "99.29", "99.50", "99.66", "99.77", "99.85", "99.91",
    "99.95", "99.97", "99.99", "99.99", "99.99", "99.99", "100.00", "100.00", "100.00", "100.00", "100.00"
]

def main():

    lines = sys.stdin.readlines()
    
    if not lines or not lines[0].strip():
        print("入力が空です", file=sys.stderr)
        sys.exit(1)
    line = lines[0].strip()
    try:
        n = int(line)
        if 0 <= n <= 40:
            print(f"{probs[n]}")
            sys.exit(0) # 正常終了
        else:
            print("負または40より大きい数です", file=sys.stderr)
            sys.exit(1) # 異常終了
    except ValueError:
        print("数字を入力してください", file=sys.stderr)
        sys.exit(1) # 異常終了

if __name__ == "__main__":
    main()
